name: Scrape
on:
    workflow_dispatch:

jobs:
    scrape-wiki:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                node-version: '14'
            - run: |
                npm install
            - run: |
                npm run build
            - name: Check for changes
              run: |
                git add .
                if git diff-index --quiet HEAD --; then
                  echo "No changes detected"
                  exit 1
                fi

            - name: Create pull request
              uses: peter-evans/create-pull-request@v3
              with:
                commit-message: 'Automated: regenerated code based on scraped wiki data'
                title: 'Automated PR: Regenerated code'
                body: '-----'
                author: 'github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>'
                branch: 'automated/scraped'
                branch-suffix: timestamp
